apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: streamlit
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: {{ .Values.service.name }}