apiVersion: v1
kind: ConfigMap
metadata:
  name: streamlit-launch-script
  namespace: streamlit
data:
  launch.sh: |
    #!/bin/bash
    apt-get update && apt-get install -y inotify-tools

    pip install streamlit==1.26.0

    while [ ! -f /app/$CODE_DIR/$ENTRYPOINT ]
    do
        echo "ENTRYPOINT NOT FOUND, SLEEPING FOR 5 SECONDS"
        echo "LOOKING FOR: /app/$CODE_DIR/$ENTRYPOINT"
        sleep 5
    done
    pip install -r /app/$CODE_DIR/requirements.txt
    
    
    DIR_TO_WATCH=/app/$CODE_DIR/
    
    while true; do
      cd /app/$CODE_DIR
    
      streamlit run /app/$CODE_DIR/$ENTRYPOINT --server.port=80 --server.address=0.0.0.0 --server.fileWatcherType=none &
      SERVER_PID=$!
    
      inotifywait -r -e modify,create,delete,move $DIR_TO_WATCH
    
      kill $SERVER_PID
    
      sleep 1
    done